# Generated by Django 3.2.25 on 2024-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultcheckerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
